name: Build and Deploy Storybook
on:
  push:
    paths: ["stories/**", "src/components/**"] # Trigger the action only when files change in the folders defined here
  repository_dispatch:
    types: [re-prod-deploy]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --pure-lockfile
        name: Install dependencies
      - run: yarn build-storybook
        name: Build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
